### ISSUE TITLE
Matrix Library

### ISSUE THREAD

**Issue by TheDocTrier** [Tankobot/personal#2]
We need to create a matrix library for general use, since I have not found native support within Lua.

**Comment by sbradley36** [comment]
So we need to create a library of matrix arithmetic functions?

**Comment by TheDocTrier** [comment]
> So we need to create a library of matrix arithmetic functions?

Exactly, I'm working on the library currently. If you check the branch associated with this issue (iss2) you'll find a commit that has my work in progress library inside. It's not very neat so I'll have to tidy it up soon.

**Comment by TheDocTrier** [comment]
Not enough reason to continue development of matrix library.
